### ISSUE TITLE
Handle combined repr attributes like `#[repr(C, u8)]` in repr checks

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#104]
https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html#explicit-repr-annotation-with-c-compatibility
![image](https://user-images.githubusercontent.com/2348618/186275867-900c0005-6179-4a2e-af26-6a6252d26a7b.png)

Currently, I suspect that `#[repr(C, u8)]` won't get detected as either `#[repr(C)]` or as `#[repr(u8)]`, which I believe can lead to both false-positives and false-negatives. Due to the false-positives, this is a bug.

H/t https://twitter.com/bitshiftmask/status/1562185690208735233 + a private Twitter account I'm not going to name, you know who you are :) Thank you both!

**Comment by SmolSir** [comment]
This was closed by merging #171.
