### ISSUE TITLE
Upload prebuilt binaries to GitHub releases

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#112]
### Describe your use case

Prebuilt binaries can cut ~2-3min from the execution time of the `cargo-semver-checks` GitHub Action. Other Rust binary crates tend to make and upload prebuilt binaries as part of the release process, and make them part of the GitHub release. We should probably follow suit.

### Describe the solution you'd like

Pre-build binaries for the most common targets and upload them to each GitHub release.

Action that might be useful: https://github.com/taiki-e/upload-rust-binary-action#example-workflow-cross-compilation

Limit the GitHub token permissions like the following: https://github.com/taiki-e/cargo-hack/blob/202e6e59d491c9202ce148c9ef423853267226db/.github/workflows/release.yml#L3-L5

Available target runners on GitHub Actions: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners

Examples from other crates:
- https://github.com/taiki-e/cargo-hack/blob/202e6e59d491c9202ce148c9ef423853267226db/.github/workflows/release.yml#L47-L84
- https://github.com/LukeMathWalker/cargo-chef/blob/main/.github/workflows/publish_binaries.yml#L18-L43
- https://github.com/LukeMathWalker/bunyan/blob/main/.github/workflows/publish_binaries.yml#L18-L35

**Comment by staniewzki** [comment]
Solved by https://github.com/obi1kenobi/cargo-semver-checks/pull/208
