### ISSUE TITLE
Initial support for querying function parameters in the schema

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#154]
Make an MVP for accessing function parameters in the schema. Aim to make it possible to write lints that detect changes in the number of parameters a function takes.

Parameter names can be changed without violating semver so are not critical to support, but are a "nice-to-have" for e.g. the [Playground](https://play.predr.ag/rustdoc). Add them to the schema if possible.

Parameter type information is a bit more difficult to represent due to #149, so feel free to ignore types for now in the interest of moving quickly.

Relevant portion of the schema:
https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/main/src/rustdoc_schema.graphql#L430-L493

**Comment by tonowak** [comment]
Implemented in https://github.com/obi1kenobi/cargo-semver-checks/pull/170. Should I close the issue?
