### ISSUE TITLE
Adding `#[must_use]` on an item

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#159]
When `#[must_use]` is added, code in downstream crates that did not use a value of that type will get a compiler lint.

New lints for existing code requires a minor version: https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#minor-change-introducing-new-lint-warningserrors

We want to support both "bare" `#[must_use]` and the form with a reason: `#[must_use = "foo bar"]`

**Comment by SmolSir** [comment]
According to [Rust Reference](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute) about `#[must_use]` attribute, the following lints have to be added:
- [x] enum_must_use_added
- [ ] struct_must_use_added
- [ ] function_must_use_added
- [ ] method_must_use_added
- [ ] trait_must_use_added
- [ ] union_must_use_added

The `union_must_use_added` lint requires schema additions before it can be implemented to close this issue.
