### ISSUE TITLE
Make `--workspace` flag enabled by default in workspaces?

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#161]
Should the `--workspace` flag be enabled by default when running in a workspace?

Right now, running `cargo semver-checks check-release` in a workspace will only check the top-level crate in the workspace, if there is one. It might not be obvious to users that this is the case, and it's plausible that users might not know that they need to add a flag like `--workspace` to check other crates as well.

**Comment by epage** [comment]
This is the same behavior as native cargo commands that operate on packages when run in a workspace.  Commands like `cargo update` and `cargo clean` operate exclusively on the workspace level and don't take a flag.

Before we can answer this, we need to answer https://github.com/obi1kenobi/cargo-semver-check/issues/86.

**Comment by obi1kenobi** [comment]
Let's stick to matching cargo's behavior on this for now.
