### ISSUE TITLE
Add integration tests through GitHub Actions

### ISSUE THREAD

**Issue by tonowak** [obi1kenobi/cargo-semver-checks#178]
### Describe your use case

Some tests might require getting data about crates from e.g. crates.io. But it is better to not require internet access during `cargo test` (for example, I might get a failed test because of no internet access or crates.io being down, which is not the fault of my changes to the code). The solution is to run those tests through GitHub Actions. Those tests would check whether cargo-semver-check works on some examples.

### Describe the solution you'd like

Described [here](https://github.com/obi1kenobi/cargo-semver-check/pull/173#issuecomment-1308966351)

### Additional Context

One of the tests would be checking whether https://github.com/obi1kenobi/cargo-semver-check/issues/147 is fixed.
It is necessary to add this test before releasing https://github.com/obi1kenobi/cargo-semver-check/pull/173

https://github.com/obi1kenobi/cargo-semver-check/issues/174 lists two commands that could also be tested. Testing some different use-cases might help prevent such bugs in the future.

**Comment by tonowak** [comment]
@staniewzki do you want to work on that?

**Comment by tonowak** [comment]
@obi1kenobi are there other issues/PRs that could be tested in this way?

**Comment by obi1kenobi** [comment]
I think these three are a solid start for now, but there will probably be more in the future: #167 is a great candidate to add as well, for example, once we've figured out what's wrong with it.

Ideally, we'd like to be able to easily add more commands and more repos in the future. We want to balance simplicity and ease of maintenance against e.g. more features, like comparing stdout in addition to exit codes.

I'd recommend figuring out what sort of design would be good to have in the long run, then identifying the minimum set of things we can build today to satisfy as much of our needs as possible while not requiring that we build everything all at once. For example, we don't need to check stdout right now, and we care about being able to plug in these tests quickly and easily much more than stdout checking.

**Comment by tonowak** [comment]
I guess this can be closed? @obi1kenobi
