### ISSUE TITLE
Improved error message when no baseline version found on crates.io

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#183]
Right now, if attempting to semver-check a crate that doesn't have a version published on `crates.io`, the error message is terse and not helpful:
```
    Updating index
     Parsing foo_bar v0.1.0 (current)
Error: foo_bar not found in registry
```

Possible improvements:
- State that the registry is crates.io specifically. Consider linking to the tracking issue for private registries (#166) in case that's where the crate is published.
- Advise the user that they may still semver-check this crate by using one of the other ways to get a baseline, for example via a git ref.

Perhaps related to #146 as well.

**Comment by era** [comment]
Hi @obi1kenobi, I would like to give it a try. If I understood correctly the error you are mentioning comes from https://github.com/obi1kenobi/cargo-semver-checks/blob/main/src/rustdoc_gen.rs#L589, given `need_retry` I imagine the error is `err.class() == git2::ErrorClass::Index && err.code() == git2::ErrorCode::NotFound`.

And for what I see on the project, the errors bubble up to the main function and force the program to exit with the error message printed. If that is the case, would something like this be ok or you have something else in mind?

```rust
while need_retry(index.update()).map_err(human_readable_message)? {
            config.shell_status("Blocking", "waiting for lock on registry index")?;
            std::thread::sleep(REGISTRY_BACKOFF);
        }
```

**Comment by obi1kenobi** [comment]
I believe that's all correct and the approach seems sound. Go for it! Thanks for giving it a try 🙌

**Comment by era** [comment]
In the end, it was more simple because there is already a check if the crate is at crates.io, so I just modified the error message. If this is not enough I can go back to the previous solution we talked about.
