### ISSUE TITLE
Lints related to function ABI changes

### ISSUE THREAD

**Issue by staniewzki** [obi1kenobi/cargo-semver-checks#260]
Original description:
- things like `extern "C" fn`: https://docs.rs/rustdoc-types/latest/rustdoc_types/enum.Abi.html
- new lints enabled by this:
  - [x] ABI kind changed, e.g. `extern "C" fn` to `extern "system" fn` (or, if `extern` is removed, to the default `extern "Rust" fn`)
  - [ ] ABI unwind ability removed, e.g. `extern "C-unwind" fn` to `extern "C" fn`
  - [ ] is moving from `extern "C" fn` to `extern "C-unwind" fn` a breaking change?
    - technically, yes, but it's like adding `#[non_exhaustive]` when it was first introduced -- it's fairly new so let's not penalize early adopters

**Comment by obi1kenobi** [comment]
Superseded by #503.
