### ISSUE TITLE
Tool fails on Windows

### ISSUE THREAD

**Issue by tonowak** [obi1kenobi/cargo-semver-checks#276]
Related: https://github.com/obi1kenobi/cargo-semver-checks-action/pull/21#issuecomment-1374964447

In short, there seems to be a path issue when comparing the crate with a baseline from the registry.

Proposed solution: try to reproduce the bug locally on Windows (if it somehow works, write a comment about it in the mentioned PR), fix it after reproducing and add an integration test (in the CI).

**Comment by obi1kenobi** [comment]
It might be a good idea to have at least one "positive" and one "negative" test (in terms of whether they're expected to find any semver issues) that run on each of our supported platforms and architectures (the ones we build binaries for).

**Comment by obi1kenobi** [comment]
Underlying cause: https://github.com/frewsxcv/rust-crates-index/issues/93

**Comment by mgr0dzicki** [comment]
Unfortunately, the tool still fails on Windows when it is run from a precompiled binary. The problem occurs only when the `.cargo/registry/index` folder does not exist at the moment of running the binary (and this is exactly the case when it is launched inside the GitHub action). I've written the test with this specific scenario: https://github.com/obi1kenobi/cargo-semver-checks/pull/389.

**Comment by mgr0dzicki** [comment]
Completed by https://github.com/obi1kenobi/cargo-semver-checks/pull/389
