### ISSUE TITLE
compiling semver-checks fails

### ISSUE THREAD

**Issue by demoray** [obi1kenobi/cargo-semver-checks#317]
### Steps to reproduce the bug with the above code

cargo install cargo-semver-checks

### Actual Behaviour
```
   --> /home/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-semver-checks-0.15.2/src/baseline.rs:387:31
    |
387 |             if err.class() == git2::ErrorClass::Index && err.code() == git2::ErrorCode::Locked {
    |                               ^^^^^^^^^^^^^^^^^^^^^^^ expected enum `git2::ErrorClass`, found enum `ErrorClass`
    |
    = note: enum `ErrorClass` and enum `git2::ErrorClass` have similar names, but are actually distinct types
note: enum `ErrorClass` is defined in crate `git2`
   --> /home/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.15.0/src/lib.rs:225:1
    |
225 | pub enum ErrorClass {
    | ^^^^^^^^^^^^^^^^^^^
note: enum `git2::ErrorClass` is defined in crate `git2`
   --> /home/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.16.1/src/lib.rs:225:1
    |
225 | pub enum ErrorClass {
    | ^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `git2` are being used?

error[E0308]: mismatched types
   --> /home/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-semver-checks-0.15.2/src/baseline.rs:387:72
    |
387 |             if err.class() == git2::ErrorClass::Index && err.code() == git2::ErrorCode::Locked {
    |                                                                        ^^^^^^^^^^^^^^^^^^^^^^^ expected enum `git2::ErrorCode`, found a different enum `git2::ErrorCode`
    |
    = note: enum `git2::ErrorCode` and enum `git2::ErrorCode` have similar names, but are actually distinct types
note: enum `git2::ErrorCode` is defined in crate `git2`
   --> /home/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.15.0/src/lib.rs:165:1
    |
165 | pub enum ErrorCode {
    | ^^^^^^^^^^^^^^^^^^
note: enum `git2::ErrorCode` is defined in crate `git2`
   --> /home/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.16.1/src/lib.rs:165:1
    |
165 | pub enum ErrorCode {
    | ^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `git2` are being used?

For more information about this error, try `rustc --explain E0308`.
error: could not compile `cargo-semver-checks` due to 2 previous errors
error: failed to compile `cargo-semver-checks v0.15.2`, intermediate artifacts can be found at `/tmp/cargo-installBVlg0U`
```

### Expected Behaviour

this to run without issue

### Generated System Information

n/a

### Build Configuration

n/a

**Comment by tonowak** [comment]
I've managed to reproduce the issue, I'm looking into it.

**Comment by tonowak** [comment]
For now I'll say that the command `cargo install cargo-semver-checks --locked`  (from https://github.com/obi1kenobi/cargo-semver-checks#quick-start ) successfully compiles the tool @demoray.

**Comment by tonowak** [comment]
@obi1kenobi I don't really understand why the tool fails to compile. When installing a non-locked version, for some reasons cargo installs two versions of `git2` -- `v0.16.1` and `v0.15.0`. But the `Cargo.toml` of the tool uses explicitly `v0.15.0`.

**Comment by tonowak** [comment]
I've tried to raise the `git2` version from `v0.15.0` to `v0.16.1` and after a local `cargo clean` I have the same compilation error, but the `v0.15.0` shouldn't be used anymore...

**Comment by obi1kenobi** [comment]
Wow. Thanks for the report @demoray, sorry you had to deal with it. We're looking into it.

Most bin crate maintainers strongly recommend `--locked` when `cargo install`-ing anything, because many of us have found that despite our best efforts, stuff like this tends to happen from time to time. Occasionally even because of semver breaks in a dependency! 😅

**Comment by tonowak** [comment]
By the way, it's quite ironic that a tool to detect semver breaks fails to compile because of semver breaks.

**Comment by obi1kenobi** [comment]
Just yet another piece of evidence for the fact that [getting semver right is hard](https://predr.ag/blog/toward-fearless-cargo-update/)!

Also, I don't currently believe this specific instance is a semver violation. We seem to somehow be pulling in and using two different major versions of the same crate, and rustc correctly argues that their types are not equivalent.

**Comment by demoray** [comment]
While this crate uses git2 v0.15.0, the latest version of crates-index uses git2 v0.16.0.

If you run `cargo update && cargo build`, you will experience this issue.

Updating this crate to use git2 v0.16.0 along with updating the dependencies using `cargo update` resolves this issue.

**Comment by obi1kenobi** [comment]
Thanks! If you have a PR ready, I'd be happy to merge it and make a new release.

I'll also look into why the versions diverged like this so we can prevent something similar from happening again in the future.

**Comment by obi1kenobi** [comment]
Unfortunately, this was a semver issue after all. While we can update our requirement to `git2 = "0.16"`, that won't prevent a similar problem in the future.

Fortunately, the upstream fix should be reasonably easy: https://github.com/frewsxcv/rust-crates-index/issues/91
