### ISSUE TITLE
New schema and lints for const and static values

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#366]
Add schema to represent `const` and `static` items. This will require new types for each in our query schema.

For now, ignore the type of the item. Adding type info to the schema is blocked on #149 which is a very hard issue (generics, lifetimes, HRTBs, effects, oh my!).

New lints enabled by this:
- pub module-level const missing
- pub module-level static missing
- const inside type's impl block missing
- mutable static became immutable static

All semver-major changes, because the item cannot be imported (it must have been renamed or deleted) and downstream is broken.

EDIT: Some of these have already been implemented, please check the rest of the thread to see what's left 👇

**Comment by obi1kenobi** [comment]
Almost completely implemented, only remaining missing piece is associated constants. Waiting to hear back in rust-lang Zulip for that: https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Rustdoc.20JSON.3A.20How.20.60const.60.20items.20are.20represented

**Comment by obi1kenobi** [comment]
Remaining lints here:
- [ ] removed const in trait 
- [ ] removed pub const inside impl
- [ ] mutable static became immutable static

**Comment by eugenesvk** [comment]
Should a change in the **value** of a pub constant be tracked in a lint in addition to a change in name/visibility?

**Comment by obi1kenobi** [comment]
I wouldn't make it a hard error like the other kinds of breaking changes, but definitely could be a very reasonable warn-level lint.

We don't currently have the means to allow users to control error/warn/ignore levels, or enable/disable lints, so I wouldn't add it right away. There are also situations where the value of the pub constant might not have changed but its rustdoc value might change from a literal value to a `_` which means something like "undetermined," so there's some nuance to worry about.

If this is something you might be interested in working toward, I'd be happy to mentor for PRs and point you in the right direction!

**Comment by eugenesvk** [comment]
Thanks for the offer, but I was only interested in this crate as a way to extract a list of constants and their types/values, and this seems to be based in your lower-level trustfall ecosystem, so to that end I've tried to patch it like https://github.com/obi1kenobi/trustfall-rustdoc-adapter/pull/280, maybe that could be a helpful base for the semver checks if you could take at look there?
