### ISSUE TITLE
New lint: trait item removed

### ISSUE THREAD

**Issue by whentze** [obi1kenobi/cargo-semver-checks#368]
Going from
```rs
pub trait Foo {
  fn foo();
}
```
to
```rs
pub trait Foo {
}
```
is a breaking change. There should be a lint for that.

**Comment by obi1kenobi** [comment]
Agreed, thanks for opening this! If you're interested in adding this lint, I'd be happy to mentor and I think it should be fairly straightforward to do.

It depends on https://github.com/obi1kenobi/trustfall-rustdoc-adapter/issues/85 which is also fairly straightforward, completely analogous to existing code.
