### ISSUE TITLE
Make pre-built binaries and upload them as releases.

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#40]
Not sure what the easiest and best way to do this is.

**Comment by epage** [comment]
See
- https://github.com/crate-ci/cargo-release/blob/master/.github/workflows/post-release.yml
- https://github.com/crate-ci/committed/blob/master/.github/workflows/release-notes.py

**Comment by staniewzki** [comment]
Seems to be solved, along with https://github.com/obi1kenobi/cargo-semver-checks/issues/112
