### ISSUE TITLE
Are environment variables for cargo inherited?

### ISSUE THREAD

**Issue by thomaseizinger** [obi1kenobi/cargo-semver-checks#443]
We've recently moved from GitHub's runners to self-hosted runners and are experiencing timeouts when `cargo semver-checks` tries to update the registry index. For example: https://github.com/libp2p/rust-libp2p/actions/runs/4819569817/jobs/8582952664

We already [use the sparse registry protocol](https://github.com/libp2p/rust-libp2p/actions/runs/4819569817/jobs/8582952664#step:16:74) but I am wondering whether that also applies for the cargo invocations made by `cargo semver-checks`?

**Comment by obi1kenobi** [comment]
I think they should be inherited (I've seen the `color=always` env var setting affect inner cargo invocations) but I don't think we have a test for it.

I'd happily merge a PR adding that kind of test into the test suite if you suspect this might be broken, though.

**Comment by thomaseizinger** [comment]
It was more of a question and we recently haven't seen these errors any more.

Will reopen if it is a problem again!
