### ISSUE TITLE
Update features heuristic to include more unstable and private feature name patterns

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#461]
As #458 documents, we have a heuristic that attempts to select "all public stable features" for a crate.

In a chat with @epage, he suggested a few more patterns that are worth adding to the heuristic, so that the "out-of-the-box" experience of cargo-semver-checks works for more crates by default:
- single-underscore (`_`) prefixed features, since IIUC those are considered private features by rustdoc
- `unstable-` and `unstable_` as prefixes, used in case a crate has multiple unstable features — IIUC used by parts of `clap` today

**Comment by era** [comment]
That seems interesting! I can tackle it next!

**Comment by obi1kenobi** [comment]
Ah sorry, you're right. I keep forgetting that GitHub has different default permissions for organization-owned vs user-owned repos. No need to assign, don't worry about it for now.

**Comment by obi1kenobi** [comment]
Resolved in #463 and shipped in v0.21.
