### ISSUE TITLE
New lints: fn changed ABI

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#503]
Lints:
- [x] `pub fn` changed ABI to an ABI of a different name, regardless of unwind: e.g. `"C"` to `"Rust"`, or `"system-unwind"` to `"C"`
  - this changes the calling convention for the function, which is a breaking change for external code that depends on it
- [x] `pub fn` changed from an unwind-capable ABI to the same-named ABI without unwind: `"C-unwind"` to `"C"` (#689)
  - this makes unwinding become UB, which is a breaking change
- [x] `pub fn` changed from a non-unwind ABI to the unwind-capable equivalent of that same ABI, e.g. `"C"` to `"C-unwind"`
  - In principle, this could be combined with the lint above, but let's not do that. Some projects may wish to enable only one of these two lints and not the other, as unwind-capable ABIs were introduced relatively recently.
- [x] `fn` marked `#[no_mangle]` or `#[export_name]` with no importable names changed to ABI of different name
  - no importable names = it's either private or pub-in-priv -- this disambiguates the lint from the `pub fn` lints
  - we have no importable names to match on, but `#[no_mangle]` or `#[export_name]` means the function's export name must be globally unique, so match on that
  - we can use the `export_name: String` property on `Function` (implemented [here](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/pull/237)), to simplify matching and account for both `#[no_mangle]` and `#[export_name]`

**Comment by obi1kenobi** [comment]
The third checkbox was handled in #650.

**Comment by qstommyshu** [comment]
Hi, I would like to try the remaining task on this issue. 
I tried to understand the pattern from the PR for the two completed task from this issue, but there are still things I don't understand, like how to check what are the fields available to a `baseline` and when and why do we choose to write `... on Function {}` at some point. Can you please give me some guidance on these please? Thanks!

**Comment by obi1kenobi** [comment]
Thanks for looking into this.

Have you had a chance to check out [the schema](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/8244b6a76f985769b222f8c62783bf3cea87dc6b/src/rustdoc_schema.graphql) these queries are written against, or tried out some queries in [the rustdoc query playground](https://play.predr.ag/rustdoc)? If not, they are good to take a peek at. Note that the playground can only query one crate at a time — it can't compare two different versions at once.

The [`baseline` edge points to `type Crate`](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/8244b6a76f985769b222f8c62783bf3cea87dc6b/src/rustdoc_schema.graphql#L18), and `Crate`'s `item` edge points to [`interface Item`](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/8244b6a76f985769b222f8c62783bf3cea87dc6b/src/rustdoc_schema.graphql#L42). We aren't looking for just about any `Item`, though, we want `Function` specifically — hence `... on Function`.

Hope this helps! Let me know if you have any more questions!

**Comment by qstommyshu** [comment]
Thanks for the guide! I think I start to have an idea on how to add a new lint now. A little issue came up when I try to add a lint.

I followed the contribution guide to add a new lint. However, it failed along with many other lints with the error code: "Once instance has previously been poisoned"
<img width="729" alt="image" src="https://github.com/obi1kenobi/cargo-semver-checks/assets/56746466/5861e95d-6703-4101-b773-e51359a3c953">

Is there a fix for these lints? Many of them fails even in a freshly cloned repo.
<img width="782" alt="image" src="https://github.com/obi1kenobi/cargo-semver-checks/assets/56746466/8f70ab34-8212-4259-87ae-6d2db4dc695e">

**Comment by obi1kenobi** [comment]
That error message means there was another, earlier error that caused the `Once` data structure to not be set up correctly. Scroll up in the log and you should see the underlying error info.

**Comment by qstommyshu** [comment]
Got it, thanks. It turns out the cause of my issue was I didn't generate the required rust doc JSON before running `cargo test`. I've fixed it and added a new lint in #683. Can you please review it when you have time? Thanks!

**Comment by pksunkara** [comment]
@obi1kenobi The second point in this is done, right? I am asking because it's not ticked.

**Comment by obi1kenobi** [comment]
Yeah! So I guess this issue seems done -- nice!

**Comment by pksunkara** [comment]
I think I got confused yesterday. I haven't seen the 3rd one implemented. Can you please double check?

**Comment by obi1kenobi** [comment]
Agreed, not done yet. Reopening.

We probably want to do a review of the lints and test cases here, to ensure they are consistent and have minimal overlap. It looks like the lint that matches on `#[export_name]` uses the raw ABI string (e.g. `"C-unwind"`) to compare, meaning it doesn't offer more granular feedback on the nature of the breakage: whether it's unwinding-related only, or something more.

It's also likely that if a function is both `#[export_name] / #[no_mangle]` and also public API, we might get duplicate lints *specifically* about ABI breakage. We should think through how we structure the lints (and write appropriate test cases) to do our best to avoid this.

**Comment by pksunkara** [comment]
Yup, agreed. That is one of the reasons I got super confused yesterday when looking at this group.
