### ISSUE TITLE
Description unclear

### ISSUE THREAD

**Issue by bestouff** [obi1kenobi/cargo-semver-checks#524]
The current one-liner description reads : "Lint your crate API changes for semver violations.".  
I find it unclear for people that don't know. How about that: "Lint your crate API changes for semantic version violations - i.e. check for breaking changes between minor versions of your crate" ?

**Comment by obi1kenobi** [comment]
Hi, thanks for the suggestion! Short descriptions are always a struggle between keeping it short and being clear and precise, and I find it quite hard to write them 😅

Unfortunately, the proposed tweak is too long. The best one-liner descriptions are generally 10 words or fewer. Any ideas that could fit in that size range?

**Comment by bestouff** [comment]
I'd say if your project's concept isn't trivial, don't be stubborn on some arbitrary limit.  
However you're right it should be shorter. As "semver" is already in the name, how about simply "Ensure crate minor revisions introduce no breaking changes" ?

**Comment by obi1kenobi** [comment]
Interesting direction. Perhaps something along the lines of "Avoid accidental breaking changes ..." or "Catch accidental breaking changes ..."?

Not sure what the second half should be, feels like it should be something like "before <something bad>" or "without <something bad>" but I can't figure out the exact words to put there. Any ideas?

Thanks for workshopping this with me! Names are hard, short taglines and descriptions are even harder 😅

**Comment by c-git** [comment]
How about just a small tweak to the original by adding the word accidental (I think it helps ppl realize it's not something they did wrong on purpose).  So it would become:

Lint your crate API changes for **accidental** semver violations

**Comment by c-git** [comment]
After some subconscious reflection I'm not sure adding accidental adds value. It might be more confusing than useful.
