### ISSUE TITLE
Use the sparse crates.io index for faster checks

### ISSUE THREAD

**Issue by Shnatsel** [obi1kenobi/cargo-semver-checks#527]
### Describe your use case

Right now cargo-semver-checks downloads the crates.io index before actually running any checks. This step alone can take several minutes, resulting in a rather long check time.

### Describe the solution you'd like

crates.io supports a [sparse index protocol](https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html) which has been the default in Cargo starting with 1.70. It would be great to use it.

There are two ways to go about it:

1. Use the `tame-index` crate in place of `crates-index`, which supports sparse index with a very easy to use API
2. Use `crates-index` v2.0, which requires you to bring your own HTTP client. This way you can save some binary size and internal complexity by using a lightweight HTTP client like `ureq` (while `tame-index` uses `reqwest` and `tokio`).

### Additional Context

`cargo audit` recently migrated to the `tame-index` crate to get sparse registry support: https://blog.rust-lang.org/inside-rust/2023/09/04/keeping-secure-with-cargo-audit-0.18.html

**Comment by obi1kenobi** [comment]
This will be resolved with the next release. I have to take care of a few other things first this week, though — major blog post incoming before the end of the week first :)

**Comment by obi1kenobi** [comment]
Published: https://github.com/obi1kenobi/cargo-semver-checks/releases/tag/v0.23.0

Let me know if you run into any issues with it, happy to reopen this if the problem comes back.

P.S.: the blog post in question, to hopefully shed some light on why I was so busy for a while 😅 https://predr.ag/blog/semver-violations-are-common-better-tooling-is-the-answer/
