### ISSUE TITLE
New lint: pub enum tuple variant adds or removes field (i.e. tuple arity changed)

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#554]
```rust
pub enum Example {
    Variant(a: i64, /* b: i64 */),
}
```
Both adding and removing the commented-out portion is a breaking change, and I don't believe we _currently_ would catch that.

**Comment by me-diru** [comment]
Hey!

I was checking out this issue. The adds and removes field cases in a pub enum are already checked with separate lints
- pub enum struct variant adds field: https://github.com/obi1kenobi/cargo-semver-checks/pull/238
- pub enum struct variant removes field: 

Do they both cover the case of tuple arity being changed, or are we looking for something different here? thanks

**Comment by obi1kenobi** [comment]
I think those lints only cover changes enums' struct variants, not changes in tuple variants. More info on different enum variant kinds: https://doc.rust-lang.org/std/keyword.enum.html

For tuple variants, we can probably have just a single lint that checks that "the tuple contains a different number of elements."

As a query, this can make use of the `@fold @transform(op: "count")` combination of directives to count how many fields each tuple has, and then use `@tag`, `@filter`, and `@output` accordingly to output the old and new counts and establish they are different. I believe one can find examples of that combination of directives in other lints' queries already.

**Comment by me-diru** [comment]
Thanks for the quick response!

I have written a lint query for the same. However, the enum tuple variant field changes are already covered in the following lints.
- https://github.com/obi1kenobi/cargo-semver-checks/blob/main/test_crates/enum_tuple_variant_field_added/old/src/lib.rs#L3 
- https://github.com/obi1kenobi/cargo-semver-checks/blob/main/test_crates/enum_tuple_variant_field_missing/old/src/lib.rs#L3

Please let me know if I am misinterpreting it; it was interesting to understand how the querying works, though; writing a lint itself is pretty intuitive

**Comment by obi1kenobi** [comment]
Ah darn, I did a pass through the lints to see if those were implemented, and yet somehow I missed them anyway. Sorry about my sloppiness that ended up wasting your time here.

You're right, this issue is completed with no further action needed. If you'd like, I can find and suggest other opportunities to write lints or otherwise contribute to the project — it would be much appreciated!

**Comment by obi1kenobi** [comment]
Some relatively easy high-impact lints here, for example: https://github.com/obi1kenobi/cargo-semver-checks/issues/633
