### ISSUE TITLE
Support semver-checking cross-compiled crates

### ISSUE THREAD

**Issue by Finomnis** [obi1kenobi/cargo-semver-checks#579]
### Steps to reproduce the bug with the above code

```bash
cargo new --lib dummy
cd dummy/
mkdir .cargo
echo "[build]" >.cargo/config.toml
echo "target = \"thumbv7em-none-eabihf\"" >>.cargo/config.toml
echo '#![no_std]' >src/lib.rs
cargo semver-checks
```

### Actual Behaviour

```
Error: Could not find expected rustdoc output for `dummy`: C:\Users\Martin\dummy\target\semver-checks\local-dummy-0_1_0\target\semver-checks\target\doc/dummy.json
```

### Expected Behaviour

The program does not error internally.

#### Software version

cargo-semver-checks 0.24.2

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
'C:\Users\Martin\.cargo\bin\cargo-semver-checks.exe' semver-checks --bugreport
```

#### cargo version

```
> cargo -V
cargo 1.73.0 (9c4383fb5 2023-08-26)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

### Build Configuration
```toml
[build]
target = "thumbv7em-none-eabihf"
```

### Additional Context

The error indicates that the expected path is:
- `target\semver-checks\local-dummy-0_1_0\target\semver-checks\target\doc\dummy.json`

However, the real path due to the cross compilation seems to be:
- `target\semver-checks\local-dummy-0_1_0\target\semver-checks\target\thumbv7em-none-eabihf\doc\dummy.json`

**Comment by obi1kenobi** [comment]
Thanks for the report. Is this functionality perhaps something you might be interested in contributing a PR for? I'd be happy to mentor and answer any questions if so.

**Comment by Finomnis** [comment]
> Thanks for the report. Is this functionality perhaps something you might be interested in contributing a PR for? I'd be happy to mentor and answer any questions if so.

I sadly don't have the time right now :/
