### ISSUE TITLE
Failure to find json file when using `build.target` config

### ISSUE THREAD

**Issue by Nemo157** [obi1kenobi/cargo-semver-checks#586]
### Steps to reproduce the bug with the above code

```console
> CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu cargo semver-checks check-release
     Parsing ureq v2.9.0 (current)
Error: Could not find expected rustdoc output for `ureq`: /run/user/1000/cargo-home/target/shared/semver-checks/target/doc/ureq.json

> ls $CARGO_HOME/target/shared/semver-checks/target/x86_64-unknown-linux-gnu/doc/ureq.json
/run/user/1000/cargo-home/target/shared/semver-checks/target/x86_64-unknown-linux-gnu/doc/ureq.json
```

### Actual Behaviour

failure

### Expected Behaviour

it looks in the correct location

#### Software version

cargo-semver-checks 0.24.0

#### Operating system

Linux 6.1.58

#### Command-line

```bash
/nix/store/90q5v5asbra0mrx9hl9ixmk9pyw5akm9-cargo-semver-checks-0.24.0/bin/cargo-semver-checks semver-checks --bugreport
```

#### cargo version

```
> cargo -V
cargo 1.76.0-nightly (6790a5127 2023-11-10)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

### Build Configuration

```
CARGO_BUILD_TARGET_DIR=/run/user/1000/cargo-home/target/shared
CARGO_HOME=/run/user/1000/cargo-home
```

**Comment by obi1kenobi** [comment]
Thanks for the report! Unfortunately I haven't had any time to look at supporting custom target directories or most kinds of other custom cargo configs. Any chance you might be up for putting together a PR for this? I'd be happy to point you in the right direction.
