### ISSUE TITLE
Improve error message when no library targets are found

### ISSUE THREAD

**Issue by sajis997** [obi1kenobi/cargo-semver-checks#723]
### Discussed in https://github.com/obi1kenobi/cargo-semver-checks/discussions/722

<div type='discussions-op-text'>

<sup>Originally posted by **sajis997** March 29, 2024</sup>
usiing the following in the pipeline

    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2

I am getting the following error:

error: no crates with library targets selected, nothing to semver-check
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 1</div>

**Comment by obi1kenobi** [comment]
We can probably make the error message a bit better here. For example:
```
error: no crates with library targets selected, nothing to semver-check
note: only library targets contain an API surface that can be checked for semver
note: skipped crates foo, bar, baz since they do not have a library target
```
