### ISSUE TITLE
CI failed for rustdoc format v32 is not support

### ISSUE THREAD

**Issue by Xuanwo** [obi1kenobi/cargo-semver-checks#823]
### Steps to reproduce the bug with the above code

In CI: https://github.com/obi1kenobi/cargo-semver-checks/actions/runs/10032296504/job/27723773802

### Actual Behaviour

CI failed for:

```shell
thread 'query::tests_lints::trait_now_doc_hidden' panicked at src/query.rs:311:14:
failed to load baseline rustdoc: Could not load ./localdata/test_data/enum_missing/old/rustdoc.json file, did you forget to run ./scripts/regenerate_test_rustdocs.sh ?

Caused by:
    rustdoc format v32 for file ./localdata/test_data/enum_missing/old/rustdoc.json is not supported
```

### Expected Behaviour

CI can pass on the newest nightly.

### Generated System Information

not related.

### Build Configuration

not related.

**Comment by Xuanwo** [comment]
I'm working on this now. The first step is adding v32 format support for `trustfall-rustdoc-adapter`: https://github.com/obi1kenobi/trustfall-rustdoc-adapter/pull/338

**Comment by obi1kenobi** [comment]
I cut new releases of `trustfall-rustdoc-adapter` and `trustfall-rustdoc` with support for the new format, and I also just opened a PR with the version-bump to make use of it in cargo-semver-checks and unbreak the nightly builds.

Thanks for the help! No pressure at all, but if you might still be interested in writing lints, I'm happy to help with that as well :)
