### ISSUE TITLE
`regenerate_test_rustdocs.sh` depends on Git

### ISSUE THREAD

**Issue by emilazy** [obi1kenobi/cargo-semver-checks#855]
### Describe your use case

We use the GitHub archives of revisions to build `cargo-semver-checks`, and we want to run the tests in CI, which requires running `scripts/regenerate_test_rustdocs.sh`. Since the exported tarballs don’t have a `.git` directory, the `git rev-parse --show-toplevel` call fails.

### Describe the solution you'd like

Use a method of finding the source root that doesn’t depend on being run in a Git repository. There are various Bash constructions for finding the directory the currently‐running script is in, which should work fine for this. I suspect Cargo may also have a command that lets you find the workspace root, too.

### Alternatives, if applicable

We’ve previously been working around that by depending on Git for tests and initializing a blank repository so that the script can find the root. I have an open pull request to switch to patching the assignment in the script directly instead, but that’s not terribly elegant either.

### Additional Context

https://github.com/NixOS/nixpkgs/pull/334718

**Comment by obi1kenobi** [comment]
I have a mild apprehension about being "too clever" with bash-isms so I figured I'd make the git check conditional, and allow the code to fall back to a bash-ism for detecting the path: see #856

I've tested it locally in a few variations and it seems to work. If you also think it looks good, I can merge it and we can give it a shot?
