### ISSUE TITLE
New lints: Changes to enum variant discriminants

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#898]
Background on discriminants: https://doc.rust-lang.org/reference/items/enumerations.html#discriminants

We're looking for three lints total:
- [x] a public API enum without an explicit `repr()` has a variant that used to have a well-defined discriminant, but no longer does:
  - We only check the "without explicit `repr()`" case here. This is because if the enum has a `repr()`, then its variants always have a well-defined discriminant so there's nothing to lint. The case when the `repr()` is removed (and therefore might un-define some discriminants) is handled by another lint.
- a public API enum's variant had its discriminant has changed from its previous value: @dmatos2012 
  - [x] the enum has an explicit representation, like `#[repr(u8)]` or `#[repr(i64)]`: #1036
  - [x] the enum does not have an explicit representation: #912 

We distinguish between the repr/no-repr cases so that we can offer better error messages. When an enum has an explicit repr, that imposes an ABI (application binary interface) constraint in addition to the API constraint. Without a repr, the *numeric* value of the discriminant is fixed but its *binary representation* is not and could be anything.

For examples of querying the `repr` properly, please look at the `enum_repr_int_changed` lint. Make sure to include test cases where the repr is `#[repr(C, i64)]` or `#[repr(u8, C)]` since both variants are allowed too. The lints must appropriately detect the integer repr in both these cases and more straightforward ones like `#[repr(i8)]`.

**Comment by dmatos2012** [comment]
Ill take the the 2nd bullet point, `a public API enum's variant had its discriminant has changed from its previous value ` lint, which will cover the two bullet points you mention :)

**Comment by dmatos2012** [comment]
> Cool, got you marked as owning that. Are you still working on #885 as well, or is that blocked on something?

[answered](https://github.com/obi1kenobi/cargo-semver-checks/issues/885#issuecomment-2325289242)

**Comment by obi1kenobi** [comment]
Ah @dmatos2012 we actually want four lints for this issue, not two. The second bullet point describes two lints, since we want to lint for "you're breaking ABI" (such as for FFI use cases) separately from "you are breaking API." That will let us make stronger statements than "may break FFI", since hedging is generally bad when reporting errors.
