### ISSUE TITLE
Supplying comma-separated features in the CLI doesn't work

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#915]
CLI args like `--baseline-features 24bits,50bits,libm` or `--current-features 24bits,50bits,libm` are interpreted as one long feature named `"24bits,50bits,libm"` instead of a comma-separated list of features.

I believe this is a divergence from how the cargo CLI handles features. Specifying the features one-at-a-time with a long CLI flag like `--baseline-features` is very clunky. We should support lists, and we should add CLI tests using the new testing framework to ensure this doesn't regress.

Bug noticed in https://github.com/obi1kenobi/cargo-semver-checks/issues/914#issuecomment-2329356250

**Comment by dmatos2012** [comment]
This looks like easy(rip) :D, will give it a shot!
