### ISSUE TITLE
Snapshot tests fail if not building in git repository

### ISSUE THREAD

**Issue by matthiasbeyer** [obi1kenobi/cargo-semver-checks#985]
https://github.com/obi1kenobi/cargo-semver-checks/blob/00a7b09de4cac65da248736b15c55478b829ac55/tests/integration_snapshots.rs#L56

For our build in nixpkgs, this line fails because there is no hash when building, so the snapshot does not match with `([HASH])`.

---

Edit: Screenshot for transparency:

![image](https://github.com/user-attachments/assets/49e11c2f-d812-43a1-88b3-3e71f8b1ca9a)

**Comment by suaviloquence** [comment]
https://github.com/obi1kenobi/cargo-semver-checks/blob/00a7b09de4cac65da248736b15c55478b829ac55/tests/integration_snapshots.rs#L55

```diff
- r"cargo-semver-checks \d+\.\d+\.\d+(-[\w\.-]+)? \(\w+(-modified)?\)",
+ r"cargo-semver-checks \d+\.\d+\.\d+(-[\w\.-]+)? (\(\w+(-modified)?\))?",
```

should work, I can make a PR later today.

**Comment by obi1kenobi** [comment]
Thank you both! Sorry for the delay, I'm finally back in the game after a bunch of travel and other things going on.
